PROJECT_STATUS_IN_PROGRESS = "进行中"
PROJECT_STATUS_PUBLISHED = "已发布"
PROJECT_STATUS_ARCHIVED = "已归档"

PROJECT_STATUS_ALIASES = {
    "IN_PROGRESS": PROJECT_STATUS_IN_PROGRESS,
    "PUBLISHED": PROJECT_STATUS_PUBLISHED,
    "ARCHIVED": PROJECT_STATUS_ARCHIVED,
}
